### ISSUE TITLE
Two different results about the same median time from open to merge for PRs

### ISSUE THREAD

**Issue by Jeanine-tw** [cncf/devstats#18]
On [page 1](https://hwameistor.devstats.cncf.io/d/27/time-to-merge-in-repository-groups?orgId=1&var-period=d7&var-repogroup_name=All&from=1645372800000&to=now), the avg value of median time (7 days MA) is 21.09 hours. While [page 2](https://hwameistor.devstats.cncf.io/d/16/opened-to-merged?orgId=1&var-period=d7&var-repogroup_name=All&from=1645372800000&to=now)  shows the same metric is 4.80 hours.

I'm confused by the two different numbers for the same metric. Is there any difference between them?

<img width="1165" alt="截屏2023-08-04 15 51 31" src="https://github.com/cncf/devstats/assets/76861242/db93808b-ada1-4692-8e9b-d1664143f969">

<img width="582" alt="截屏2023-08-04 15 50 46" src="https://github.com/cncf/devstats/assets/76861242/489f2d94-f5c6-4339-a496-a747537361bc">

**Comment by lukaszgryglicki** [comment]
Hi, will take a look today or on Monday, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
On it, comparing SQLs for those two metrics and trying to figure out what cause the difference, but when you look at the last value of the median in both charts - they are the same, and the first `with` clause used in them gives the same data for all-time PRs, so there must be something else - will update when I know what.

**Comment by lukaszgryglicki** [comment]
I see what the problem is:
We have a table `gha_pull_requests` storing PRs data and we also have `gha_issues_pull_requests` (I won't dive into details but every PR on GitHub is also an issue - means part of its data is stored on the issue object, in that `gha_issues_pull_requests` we store connection from PR to its corresponding issue data). For some reason unknown for me many PRs do not have connection to issues, see this:
```
hwameistor=# select count(distinct pull_request_id) from gha_issues_pull_requests;
 count 
-------
   339
(1 row)

hwameistor=# select count(distinct id) from gha_pull_requests;
 count 
-------
  1146
(1 row)

hwameistor=# select count(distinct id) from gha_pull_requests where id not in (select pull_request_id from gha_issues_pull_requests);
 count 
-------
   807
(1 row)
```

One of those two dashboards metrics takes into account only PRs that also have issue data, while another just takes PRs. I can fix it by removing reference to the issues part as this particular dashboard is not using any issue data, will create a fix soon, metrics used by both dashboards are (just FYI if u r interested):
- https://github.com/cncf/devstats/blob/master/metrics/shared/time_metrics.sql.
- https://github.com/cncf/devstats/blob/master/metrics/shared/opened_to_merged.sql

**Comment by lukaszgryglicki** [comment]
This is fixed, see: [1st](https://hwameistor.devstats.cncf.io/d/27/time-to-merge-in-repository-groups?orgId=1&var-period=d7&var-repogroup_name=All&from=1645372800000&to=now&viewPanel=8) and [2nd](https://hwameistor.devstats.cncf.io/d/16/opened-to-merged?orgId=1&var-period=d7&var-repogroup_name=All&from=1645372800000&to=now&viewPanel=2):

<img width="2351" alt="Zrzut ekranu 2023-08-7 o 10 50 07" src="https://github.com/cncf/devstats/assets/2469783/62e05de1-005a-49ca-864c-f9eea05681c4">
<img width="2351" alt="Zrzut ekranu 2023-08-7 o 10 50 17" src="https://github.com/cncf/devstats/assets/2469783/7abc5b64-16ca-47bb-b3ac-01edd9a1d397">

**Comment by Jeanine-tw** [comment]
thanks for your efforts!
