### ISSUE TITLE
[bug]: Data inconsistency on different pages

### ISSUE THREAD

**Issue by asmitbm** [cncf/devstats#21]
I was trying to find my devstats score, but it seems that there's either a bug, or I haven't clearly understood how to view the data.

Here are some screenshots

### My data isn't visible
![Screenshot (657)](https://github.com/cncf/devstats/assets/81866614/3239121f-aefc-403d-8c3e-c4a42a19fcad)

### My profile is visible with the score of "227" when I filter the country to India.
![Screenshot (655)](https://github.com/cncf/devstats/assets/81866614/08342483-6601-4a1c-b91d-739f1df922e0)

### My profile isn't visible when country is set to "All"
![Screenshot (656)](https://github.com/cncf/devstats/assets/81866614/c251cfec-336e-46be-8db5-0e40251d352f)

Is there any other repo where I have to update my profile/data?

**Comment by lukaszgryglicki** [comment]
Can you provide a link ? I mean which project is it?
I will check on monday, not all dashboards are showing the same stats, 1st one is definitely a bug which I will fix. One I have links I'll check, make sure it is correct and explaing what exactly is the number on each of them.

**Comment by asmitbm** [comment]
> Can you provide a link ? I mean which project is it? I will check on monday, not all dashboards are showing the same stats, 1st one is definitely a bug which I will fix. One I have links I'll check, make sure it is correct and explaing what exactly is the number on each of them.

So the project is ORAS: 
* [GitHub Link](https://github.com/oras-project)
* [Devstats](https://oras.devstats.cncf.io/) 
* [My devstats score of ORAS](https://all.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=ORAS&var-country_name=All#:~:text=15-,asmitbm,-144) 

This is the link with "no data": [User Statistics](https://all.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=y&var-metric=contributions&var-repogroup_name=All&var-users=%22asmitbm%22)

And this is the link with the country filter "India", which shows my score as 227: [Developer Activity Counts](https://all.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=India)

**Comment by lukaszgryglicki** [comment]
Thanks, I'm checking this.

**Comment by lukaszgryglicki** [comment]
So, a couple of things:
- You are providing links in the "All CNCF" DevStats instance - in one link you selected "Repository group/Project": "ORAS" while in another you selected "All", also one has country selected "All" while another has "India" - this can cause differences because we are counting everything using HLL (HypeLogLog) functions which are "count approximate" - the difference is too big so I will check it, but just letting you know.
- Also in the "All CNCF" instance we do NOT list all people/contributions in all dashboards as the amount of data would be too big, we truncate the data. You can always use `ORAS` specific [DevStats instance](https://oras.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m) to dive into the deepest details.
- "No data is an issue" that I will look into. I will also make sure all data is refreshed regarding your contributions in the "All CNCF" instance and "ORAS" instance in different repo groups "All" vs. "ORAS" and countries "All" vs. India.

WIll update you soon.

**Comment by lukaszgryglicki** [comment]
Regarding no data [here](https://all.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=y&var-metric=contributions&var-repogroup_name=All&var-users=All) - you can only select users from the drop-down - not all, looks like your user [asmitbm](https://github.com/asmitbm) is not in top users in `All CNCF` projects combined - I will check why and update, but I guess you don't have enough contributions to get to that list in "All CNCF projects" combined instance. I will check your affiliations entry for companies, country, I'll check your contributions counts on the DBs and update.

**Comment by lukaszgryglicki** [comment]
This is your overall stat in the `All CNCF` database:
```
allprj=# select * from gha_actors where login = 'asmitbm';
          id          |  login  |        name        | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
----------------------+---------+--------------------+------------+-----+----------+----+-----------+--------------+-----
             81866614 | asmitbm | Asmit Malakannawar | in         |     |          |    |           | India        |    
 -8395915216668117200 | asmitbm | Asmit Malakannawar | in         |     |          |    |           | India        |    
(2 rows)

allprj=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where login = 'asmitbm');
       actor_id       | company_name | original_company_name |       dt_from       |        dt_to        | source 
----------------------+--------------+-----------------------+---------------------+---------------------+--------
             81866614 | Independent  | Independent           | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
 -8395915216668117200 | Independent  | Independent           | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
(2 rows)

allprj=# select count(*) from gha_events where actor_id in  (select id from gha_actors where login = 'asmitbm');
 count 
-------
   303
(1 row)
```

And in `ORAS`:
```
oras=# select * from gha_actors where login = 'asmitbm';
    id    |  login  |        name        | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
----------+---------+--------------------+------------+-----+----------+----+-----------+--------------+-----
 81866614 | asmitbm | Asmit Malakannawar | in         |     |          |    |           | India        |    
(1 row)

oras=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where login = 'asmitbm');
 actor_id | company_name | original_company_name |       dt_from       |        dt_to        | source 
----------+--------------+-----------------------+---------------------+---------------------+--------
 81866614 | Independent  | Independent           | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | user
(1 row)

oras=# select count(*) from gha_events where actor_id in  (select id from gha_actors where login = 'asmitbm');
 count 
-------
   294
(1 row)
```

Here is your per-project stat in `All CNCF`:
```
allprj=# select r.repo_group, count(e.id), min(e.created_at), max(e.created_at) from gha_events e, gha_repos r where e.repo_id = r.id and e.dup_repo_name = r.name and e.actor_id in (select id from gha_actors where login = 'asmitbm') group by r.repo_group;
 repo_group | count |         min         |         max         
------------+-------+---------------------+---------------------
 Buildpacks |    26 | 2021-08-19 07:01:25 | 2021-10-06 17:00:22
 CNCF       |    76 | 2021-08-19 07:17:42 | 2023-08-05 14:32:00
 KubeEdge   |     1 | 2023-02-04 06:55:19 | 2023-02-04 06:55:19
 Meshery    |     1 | 2022-06-13 14:02:03 | 2022-06-13 14:02:03
 ORAS       |   199 | 2023-02-04 06:53:51 | 2023-07-27 10:21:00
(5 rows)
```

In `ORAS`:
```
oras=# select r.repo_group, count(e.id), min(e.created_at), max(e.created_at) from gha_events e, gha_repos r where e.repo_id = r.id and e.dup_repo_name = r.name and e.actor_id in (select id from gha_actors where login = 'asmitbm') group by r.repo_group;
      repo_group       | count |         min         |         max         
-----------------------+-------+---------------------+---------------------
 oras-project/oras-go  |     8 | 2023-02-11 06:37:22 | 2023-02-11 12:37:23
 oras-project/oras-www |   286 | 2023-02-04 06:53:51 | 2023-07-27 10:21:00
(2 rows)
```

I think ORAS moved to a new org some time back, and `All CNCF` instance was not updated, will now merge ORAS db into all cncf and then regenerate metrics.

**Comment by lukaszgryglicki** [comment]
Also, you requested yearly stats while you started contributing in 2/2023 - so there is no complete year once you started - yearly stats are generated when a year passes, you will see your data in yearly stats only in 2024, you should select a smaller date period like a monthly or `7 Days MA`.

**Comment by lukaszgryglicki** [comment]
So, I've regenerated the `ORAS` instance and now you can see yourself in the following links:
User stats:
- Daily user stats: https://oras.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=d&var-metric=contributions&var-repogroup_name=All&var-users=%22asmitbm%22&from=now-1y&to=now.
- 7 Days MA: https://oras.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=d7&var-metric=contributions&var-repogroup_name=All&var-users=%22asmitbm%22&from=now-1y&to=now
- Up to quarter: https://oras.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=q&var-metric=contributions&var-repogroup_name=All&var-users=%22asmitbm%22&from=now-1y&to=now

Developer activity counts (160):
- `Country = All`: https://oras.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All.
- `Country = India`: https://oras.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=India.
- `Country = India, repo group = oras-go`: https://oras.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=oras-project%2Foras-go&var-country_name=India.
- `Country = India, repo group = oras-www`: https://oras.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=oras-project%2Foras-www&var-country_name=India.


I'm now also updating the `All CNCF` instance, but because it contains data from all projects combined - it will take many hours to complete.
Also, note that number might be slightly off because of the `count approx.` usage everywhere (hypeLogLog) and this is OK and expected.

**Comment by lukaszgryglicki** [comment]
This is fixed, I'll recheck `All CNCF` tomorrow to see the numbers, closing this for now, pls reopen if there is anything else that needs to be done here.

**Comment by asmitbm** [comment]
Thank you so much for the detailed explaination. Now I understood how devstats works :))
