### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by UriZafrir** [cncf/devstats#55]
Hi,
I’m trying to use devstats - [all.devstats.cncf.io](http://all.devstats.cncf.io/) to see for each company which commits were made to which cncf projects.
this can help me see what is the open source stack for each company..
is there a dashboard for this?
if not, which parameters should I choose for this?
I think it could be interesting for the community.
![image](https://github.com/cncf/devstats/assets/35652384/d373e6d1-cd2d-4436-a596-2b13c51f0880)

**Comment by lukaszgryglicki** [comment]
- Commits for given CNCF project and company: https://all.devstats.cncf.io/d/56/company-commits-table?orgId=1.
- General commits per company: https://all.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=commits.
- Company commits in time range: https://all.devstats.cncf.io/d/83/company-contribution-counts-in-repository-groups?orgId=1&var-period_name=Last%20decade&var-metric=commits&var-company_name=Independent&var-company=independent.
- Commits counts by company and project (repo group): https://all.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=commits&var-repogroup_name=All&var-country_name=All&var-companies=All.

If there is anything else needed, please describe what exactly is needed and I can generate a custom report for you, or we can consider adding a new dashboard if needed.


Generally look for dashboards related to companies (company in their name or `companies` tag) and by repository groups (repository group is a single CNCF project in case of [All CNCF](http://all.devstats.cncf.io/) DevStats instance).

**Comment by UriZafrir** [comment]
Hi, thank you for your quick answer.
Indeed, using "company-contribution-counts-in-repository-groups", I am able to see per company what are the number of it's commits per project. I can choose one company at a time. 

I think it might be interesting for the community (or just for me) to be able to compare companies' commits per repo - maybe a dashboard of a bar chart sorted by company (one bar per company) that shows the number of commits a company has per project. This could be interesting because then we can understand the "CNCF" projects stack it's likely using.

Also I think the "rank" column in the default query is not really necessary if they are sorted by number of commits... I switched the "rank" column it with the "value" column. So another suggestion would be to switch them in the default query.

**Comment by lukaszgryglicki** [comment]
I will check this tomorrow, but even now - LMK if you want me to add any new dashboard or not? And if so, then I would need specs for that dashboard - cc @caniszczyk

**Comment by lukaszgryglicki** [comment]
`I think it might be interesting for the community (or just for me) to be able to compare companies' commits per repo `

- [All CNCF](http://all.devstats.cncf.io/) has per-project granularity, so each `repository group` is a project in this DevStats instance.
- You can go to a specific project, like for example [Prometheus](https://prometheus.devstats.cncf.io/) and when on a specific project, then single repository group maps (by default) to each repo or organization within a given project (unless defined otherwise [here](https://prometheus.devstats.cncf.io/d/68/repository-groups?orgId=1)).


`maybe a dashboard of a bar chart sorted by company (one bar per company) that shows the number of commits a company has per project. This could be interesting because then we can understand the "CNCF" projects stack it's likely using`:

- there is something similar, but showing across time: [Prometheus](https://prometheus.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=m&var-metric=commits&var-repogroup_name=All&var-companies=All&from=1427839200000&to=1554155999000), [All CNCF](https://all.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=m&var-metric=commits&var-repogroup_name=All&var-companies=All&from=1427839200000&to=1554155999000)). There is also this [one](https://grpc.devstats.cncf.io/d/74/contributions-chart?orgId=1&var-period=m&var-metric=commits&var-repogroup_name=All&var-country_name=All&var-company_name=All&var-company=all) (you can select metric type, repository group and company from drop-downs).


`Also I think the "rank" column in the default query is not really necessary if they are sorted by number of commits... I switched the "rank" column it with the "value" column. So another suggestion would be to switch them in the default query.`

- it is needed and was requested by the community so we can see who is 10th, list top 30, etc.

**Comment by UriZafrir** [comment]
As I understand from your response, there is something similar to what I'm asking but not what I'm asking.
Regarding you earlier response, yes, creating a new dashboard would be interesting for me. Which specs do you need?

**Comment by lukaszgryglicki** [comment]
Specs:
- should it be a tabular dashboard (like those with `table` tag) or a time-series dashboard?
- what should be in drop-downs (like selecting repository group, company name, etc.) - basically what are filters/parameters for it: possibly repo drop down (with All option), company drop-down (with All option). And in case of tabular dashboards "time range" - like last year, last decade, version X - Y, etc.
- what should be displayed in the dashboard - chart? if chart then what kind: line, bar, multiple values, single value? table? if table then what columns are needed? what are rows?
- is only for `All CNCF` instance or maybe for all projects, `Kubernetes` needs approval from the community as they have very specialised set of dashboards.
- do you want this as a new dashboard, or maybe you just want a custom report - just for you - in that case I can just prepare a correct SQL query, execute it and give you the data you want.

For new dashboard I would need a green light from @caniszczyk to start working on it as it will probably take a day or two to implement.

**Comment by UriZafrir** [comment]
I guess to decide if this is a dashboard or a custom query we first need to know if this feature is interesting to anyone else but me. Is there a place to suggest it to anyone else to see the response of the community?

Specs as I understand:
A tabular dashboard (not time series).
Repo drop down (with All option), company drop-down (with All option), time range dropdown - with last week, last month, last year, last decade, etc. I guess its also all options.
As I wrote, a bar chard, with each bar representing a company, with all its commits by project (with colors). For example the google bar will contain commits for kubernetes, helm, etc stacked by colors. Hope its clear. So when viewing the entire dashboard one will know for each company what are it's commits by project.
I think its only relevant to all cncf instance.

**Comment by lukaszgryglicki** [comment]
Specs are clear, now this is only the question of - do we need a separate dashboard for this, or is this OK that I will generate a custom report for this.

cc @caniszczyk - you can also ask on slack channel [#devstats](https://kubernetes.slack.com/archives/C9A0P0GPK) for example...

**Comment by UriZafrir** [comment]
I have no problem putting it on the slack channel #devstats but it seems it's archived

**Comment by lukaszgryglicki** [comment]
Hmm I don't see that it is archived:
<img width="1697" alt="Zrzut ekranu 2024-04-5 o 15 28 56" src="https://github.com/cncf/devstats/assets/2469783/7e779e11-e509-4132-bda9-fbc1441bceea">
<img width="1681" alt="Zrzut ekranu 2024-04-5 o 15 29 19" src="https://github.com/cncf/devstats/assets/2469783/a35f033a-ce5a-4c2f-9c72-379808b3125b">

I can provide a custom report for you next week, and if there is a decision that we also need a dashboard for this, I can then create one based on already generated report (its underlying query, etc.) - makes sense?

**Comment by UriZafrir** [comment]
correct. I joined the channel and posted the idea.
OK about the custom report. Thanks!

**Comment by lukaszgryglicki** [comment]
Will do on Monday.

**Comment by lukaszgryglicki** [comment]
On it - will generate a custom report and provide details here.

**Comment by lukaszgryglicki** [comment]
I've added a [report query](https://github.com/cncf/devstats-reports/blob/master/sql/company_project_commits_stats.sql) that calculates the requested data.
I've described [here](https://github.com/cncf/devstats-reports/tree/master?tab=readme-ov-file#commits-stats-for-projects-and-companies) (section `Commits stats for projects and companies`) how to use it in the reporting pod.
I've generated a CSV file with results for limiting number of companies and projects to 50, so you can see top 50 companies in each of top 50 projects and top 50 projects in each of top 50 companies. I've generated data for all time (1/1/2014 - 1/1/2025).
Here is the CSV:
[company_project_commits_stats.csv](https://github.com/cncf/devstats/files/14903530/company_project_commits_stats.csv)

I will also upload this to Google sheet and create some example chart and put a link here.

**Comment by lukaszgryglicki** [comment]
[Here](https://docs.google.com/spreadsheets/d/1aW7_NZi9bxJPqGOWMLXEGoewdqdjquJtlOzmo5V8NQU/edit?usp=sharing) is the google sheet with data, you can create any chart you need from it.
It has two sheets showing the same data, but organised differently.
Your request was for data in `By Company` sheet, it contains.

I'm skipping any bot activities and I'm not including `Independent` affiliation which is not a real company, I'm also skipping `CNCF` projects which is just a statistics for CNCF itself.

- `column A` - `Company's name` (ordered by all commits made by company across all CNCF projects) - I'm including top 50 companies. The sheet is sorted from top committing to 50th committing company. We are skipping special entries like `Independent`, `(Robots)` and unaffiliated/unknown commits (commits coming from contributors for whom affiliations are unknown at given commit's timestamp).

- `column B` - `CNCF project name` that company commits to. It is sorted by the number of commits made by this company and then project for which that company makes more commits. Up to 50 projects can show here - if given company commits to at least 50 different projects. We are skipping special `CNCF` internal project.

- `column C` - `Commits` - how many commits a given company made for a given CNCF project since 1/1/2014 to 1/1/2025 (basically all-time).

- `column D` - `All company's commits` - number of all commits that this company has made to all CNCF projects (excluding special `CNCF` project).
- `column E` - `All project's commits` - number of all commits that given CNCF project has in a given filtering context (all time range, no bots, no `Independent`/`(Robots)` or unknown/unaffiliated commits).
- `column F` - `Percent of all company's commits` - percent of all commits made by this company dedicated to a given CNCF project) - this is basically `column C` / `column D` percent.
- `column G` - `Percent of all project's commits` - how many percent for a given CNCF project is coming from this company - this is basically `column C` / `column E` percent.

Another sheet is `By Project` and it is showing the same data but from project's perspective not company, so the fist column there is a project and then split by companies (the opposite of `By Company` where the 1st column is a company and then split by project).

I'm not sure what exact chart is needed, but all data is in the linka nd I've allowed full edit for anybody with the link, so feel free to create any chart you need or just duplicate and do whatever is needed with this data.


For creating a dedicated dashboard that would be doing something similar I need a `green light` from @caniszczyk and more people's requests to do so - this si because we don't have a dashboard of this type yet (stacked bar charts not using timestamps but one column for separate "stacks" and then another columns for "stacking items") - so it will take a considerable amount of time to implement - plus I think that aggregated data will very seldom change, so generating this `on request` even twice a year will be a simpler solution that adding one more complex dashboard.

**Comment by lukaszgryglicki** [comment]
I'm closing this for now - I've added label `needs-decision` for this.

**Comment by UriZafrir** [comment]
thank you.
I managed to generate a really simple graph with python and plotly.
I think this is really interesting.... Would love to get that implemented. I can also try to help.

```
import pandas as pd
import plotly.express as px
df = pd.read_csv('company_project_commits_stats.csv')
fig = px.bar(df, x="company", y="all_company_commits", log_y=True,color="project", text_auto=True)
fig.update_xaxes(categoryorder='total descending')
fig.show()
```
![newplot (1)](https://github.com/cncf/devstats/assets/35652384/0996c128-09de-4ae6-83ba-e218c69fa0c1)
![newplot](https://github.com/cncf/devstats/assets/35652384/470c8635-386a-48d9-a3a1-c21026e7f38a)

**Comment by lukaszgryglicki** [comment]
Looking very good, thanks for this!

**Comment by lukaszgryglicki** [comment]
OK, closing this, please reopen if there is anything else needed.
